version: 1.0.{build}
branches:
  only:
  - master
before_build:
- ps: nuget restore ./DogeNews/DogeNews.sln
build:
  project: ./DogeNews/DogeNews.sln
  verbosity: minimal
notifications:
- provider: Email
  to:
  - stefankoserkov@gmail.com
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true

environment:
  COVERALLS_REPO_TOKEN:
    secure: fY7ejJ5zJHUqlaOgQrIwsBDDowxRetuy9
